<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHKKzZop\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHKKzZop/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHKKzZop.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHKKzZop\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerHKKzZop\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'HKKzZop',
    'container.build_id' => '86cd6395',
    'container.build_time' => 1573841098,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHKKzZop');
